/**
 * APIs externas retornam nomes de seleções em inglês.
 * Mapeamento para exibição em português brasileiro.
 */
const NATIONAL_TEAM_NAMES_PT_BR: Record<string, string> = {
  Afghanistan: 'Afeganistão',
  Albania: 'Albânia',
  Algeria: 'Argélia',
  Andorra: 'Andorra',
  Angola: 'Angola',
  Argentina: 'Argentina',
  Armenia: 'Armênia',
  Australia: 'Austrália',
  Austria: 'Áustria',
  Azerbaijan: 'Azerbaijão',
  Bahrain: 'Bahrein',
  Bangladesh: 'Bangladesh',
  Belarus: 'Bielorrússia',
  Belgium: 'Bélgica',
  Bolivia: 'Bolívia',
  'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
  'Bosnia & Herzegovina': 'Bósnia e Herzegovina',
  Brazil: 'Brasil',
  Bulgaria: 'Bulgária',
  Cameroon: 'Camarões',
  Canada: 'Canadá',
  Chile: 'Chile',
  China: 'China',
  Colombia: 'Colômbia',
  'Costa Rica': 'Costa Rica',
  Croatia: 'Croácia',
  Cuba: 'Cuba',
  'Czech Republic': 'República Tcheca',
  Czechia: 'Tchéquia',
  Denmark: 'Dinamarca',
  Ecuador: 'Equador',
  Egypt: 'Egito',
  England: 'Inglaterra',
  Estonia: 'Estônia',
  Finland: 'Finlândia',
  France: 'França',
  Georgia: 'Geórgia',
  Germany: 'Alemanha',
  Ghana: 'Gana',
  Greece: 'Grécia',
  Guatemala: 'Guatemala',
  Honduras: 'Honduras',
  Hungary: 'Hungria',
  Iceland: 'Islândia',
  India: 'Índia',
  Indonesia: 'Indonésia',
  Iran: 'Irã',
  Iraq: 'Iraque',
  Ireland: 'Irlanda',
  Israel: 'Israel',
  Italy: 'Itália',
  'Ivory Coast': 'Costa do Marfim',
  "Côte d'Ivoire": 'Costa do Marfim',
  Jamaica: 'Jamaica',
  Japan: 'Japão',
  Jordan: 'Jordânia',
  Kazakhstan: 'Cazaquistão',
  'Korea Republic': 'Coreia do Sul',
  'South Korea': 'Coreia do Sul',
  Kosovo: 'Kosovo',
  Latvia: 'Letônia',
  Lithuania: 'Lituânia',
  Luxembourg: 'Luxemburgo',
  Malaysia: 'Malásia',
  Mexico: 'México',
  Montenegro: 'Montenegro',
  Morocco: 'Marrocos',
  Netherlands: 'Holanda',
  'New Zealand': 'Nova Zelândia',
  Nigeria: 'Nigéria',
  'North Macedonia': 'Macedônia do Norte',
  'Northern Ireland': 'Irlanda do Norte',
  Norway: 'Noruega',
  Panama: 'Panamá',
  Paraguay: 'Paraguai',
  Peru: 'Peru',
  Poland: 'Polônia',
  Portugal: 'Portugal',
  Qatar: 'Catar',
  Romania: 'Romênia',
  Russia: 'Rússia',
  'Saudi Arabia': 'Arábia Saudita',
  Scotland: 'Escócia',
  Senegal: 'Senegal',
  Serbia: 'Sérvia',
  Slovakia: 'Eslováquia',
  Slovenia: 'Eslovênia',
  'South Africa': 'África do Sul',
  Spain: 'Espanha',
  Sweden: 'Suécia',
  Switzerland: 'Suíça',
  Thailand: 'Tailândia',
  Tunisia: 'Tunísia',
  Turkey: 'Turquia',
  Ukraine: 'Ucrânia',
  'United Arab Emirates': 'Emirados Árabes Unidos',
  'United States': 'Estados Unidos',
  USA: 'Estados Unidos',
  Uruguay: 'Uruguai',
  Venezuela: 'Venezuela',
  Vietnam: 'Vietnã',
  Wales: 'País de Gales',
}

const COMPETITION_NAMES_PT_BR: Record<string, string> = {
  'World Cup': 'Copa do Mundo',
  'FIFA World Cup': 'Copa do Mundo',
  'Copa America': 'Copa América',
  'Copa América': 'Copa América',
  'UEFA Champions League': 'Liga dos Campeões',
  'Champions League': 'Liga dos Campeões',
  'UEFA Europa League': 'Liga Europa',
  'Europa League': 'Liga Europa',
  'Premier League': 'Premier League',
  'Serie A': 'Série A',
  'La Liga': 'La Liga',
  'Bundesliga': 'Bundesliga',
  'Ligue 1': 'Ligue 1',
  'World Cup Qualification': 'Eliminatórias da Copa do Mundo',
  'World Cup Qualification - CONMEBOL': 'Eliminatórias da Copa - CONMEBOL',
  'World Cup Qualification - UEFA': 'Eliminatórias da Copa - UEFA',
  'Friendlies': 'Amistosos',
  'International Friendly': 'Amistoso Internacional',
  'CONMEBOL Sudamericana': 'Copa Sul-Americana',
  'CONMEBOL Libertadores': 'Libertadores',
}

/** Termos de busca em PT-BR → termo para consultar na API (inglês) */
const SEARCH_ALIASES_PT_TO_EN: Record<string, string> = {
  brasil: 'Brazil',
  alemanha: 'Germany',
  frança: 'France',
  franca: 'France',
  espanha: 'Spain',
  inglaterra: 'England',
  holanda: 'Netherlands',
  suíça: 'Switzerland',
  suica: 'Switzerland',
  uruguai: 'Uruguay',
  paraguai: 'Paraguay',
  colômbia: 'Colombia',
  colombia: 'Colombia',
  argentina: 'Argentina',
  peru: 'Peru',
  chile: 'Chile',
  equador: 'Ecuador',
  bolívia: 'Bolivia',
  bolivia: 'Bolivia',
  venezuela: 'Venezuela',
  portugal: 'Portugal',
  itália: 'Italy',
  italia: 'Italy',
  bélgica: 'Belgium',
  belgica: 'Belgium',
  croácia: 'Croatia',
  croacia: 'Croatia',
  dinamarca: 'Denmark',
  suécia: 'Sweden',
  suecia: 'Sweden',
  noruega: 'Norway',
  polônia: 'Poland',
  polonia: 'Poland',
  méxico: 'Mexico',
  mexico: 'Mexico',
  'estados unidos': 'United States',
  eua: 'United States',
  'coreia do sul': 'South Korea',
  japão: 'Japan',
  japao: 'Japan',
  catar: 'Qatar',
  marrocos: 'Morocco',
  senegal: 'Senegal',
  nigéria: 'Nigeria',
  nigeria: 'Nigeria',
  cameroon: 'Cameroon',
  camarões: 'Cameroon',
  camaroes: 'Cameroon',
  gana: 'Ghana',
  tunísia: 'Tunisia',
  tunisia: 'Tunisia',
  egito: 'Egypt',
  irã: 'Iran',
  ira: 'Iran',
  'arábia saudita': 'Saudi Arabia',
  'arabia saudita': 'Saudi Arabia',
  austrália: 'Australia',
  australia: 'Australia',
  'nova zelândia': 'New Zealand',
  'nova zelandia': 'New Zealand',
}

function normalizeKey(value: string): string {
  return value.trim().toLowerCase()
}

export function resolveApiSearchQuery(query: string): string {
  const normalized = normalizeKey(query)
  return SEARCH_ALIASES_PT_TO_EN[normalized] ?? query.trim()
}

export function translateTeamNameToPtBr(name: string): string {
  const trimmed = name.trim()
  return NATIONAL_TEAM_NAMES_PT_BR[trimmed] ?? trimmed
}

export function translateCompetitionToPtBr(name: string): string {
  const trimmed = name.trim()
  return COMPETITION_NAMES_PT_BR[trimmed] ?? trimmed
}

export function isNationalTeamName(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(NATIONAL_TEAM_NAMES_PT_BR, name.trim())
}
